#' Plot a stamenmap from bbox
#' 
#' @param bbox Boundaries box generated by \link{get_bbox_from_gpx} or
#'   any other Boundaries box tool
#'   
#' @importFrom ggmap get_stamenmap ggmap
#' @export
bbox_map <- function(bbox) {
  huez_map <- ggmap::get_stamenmap(bbox = bbox,
                                   zoom = 13,
                                   maptype = "terrain")
  
  # Check the map covers your GPX file
  ggmap::ggmap(huez_map)
}