#' Generate an elevation matrix from boundary box
#' 
#' @param bbox Boundaries box as generated by \link{get_bbox_from_gpx_table}
#' 
#' @return A matrix with the latitude in columns and the longitude in rows and the elevation
#'   as values (in m)
#' @export
#' @importFrom magrittr %>%
get_elevdata_from_bbox <- function(bbox) {
  
  # Download raw data from SRTM
  data_raw <- .get_raw_elevdata_from_bbox(bbox)
  elevation_matrix <- .get_elmatdata_matrix_from_raw(data_raw)
  elevation_labels <- .get_elmat_labels_from_raw(data_raw)
  
  # Get filering indeces by bbox
  elmat_bbbox_lon <- intersect(
    which(elevation_labels[[1]] > bbox[1, "min"]),
    which(elevation_labels[[1]] < bbox[1, "max"])
  )
  
  elmat_bbbox_lat <- intersect(
    which(elevation_labels[[2]] > bbox[2, "min"]),
    which(elevation_labels[[2]] < bbox[2, "max"])
  )
  
  # label the elevation matrix by the coordinates
  elmat_df <- as.data.frame(t(elevation_matrix))
  elmat_df <- cbind(elmat_df, elevation_labels$deg_elmat_lat) %>% as.data.frame
  elmat_df <- rbind(elmat_df, elevation_labels$deg_elmat_lon) %>% as.data.frame
  
  # Filter the data by indeces 
  elmat_filtered <- elmat_df[
    c(elmat_bbbox_lat, dim(elmat_df)[1]),
    c(elmat_bbbox_lon, dim(elmat_df)[2])
    ]
  
  # Remove the data and make it colnames
  colnames(elmat_filtered)[1:(dim(elmat_filtered)[2]-1)] <- elmat_filtered[
    dim(elmat_filtered)[1],
    1:(dim(elmat_filtered)[2]-1)
    ]
  colnames(elmat_filtered)[length(colnames(elmat_filtered))] <- "deg_elmat_lat"
  return(elmat_filtered)
}

#' @noRd
#' @importFrom raster getData
.get_raw_elevdata_from_bbox <- function(bbox) {
  # Get elevation data
  return(raster::getData("SRTM", lon = bbox[1, 1], lat = bbox[2, 2]))
}

#' @noRd
#' @importFrom raster extract extent
.get_elmatdata_matrix_from_raw <- function(srtm_data) {
  return(matrix(
    raster::extract(srtm_data, raster::extent(srtm_data), buffer = 1000),
    nrow = ncol(srtm_data), ncol = nrow(srtm_data)))
}

.get_elmat_labels_from_raw <- function(srtm_data) {
  # Create a vector with the long/lat coordinates of the elmat
  return(list(
    deg_elmat_lon = seq(from = srtm_data[[1]]@extent@xmin, to = srtm_data[[1]]@extent@xmax - 5/6000, by = 5/6000),
    deg_elmat_lat = seq(from = srtm_data[[1]]@extent@ymax - 5/6000, to = srtm_data[[1]]@extent@ymin, by = -5/6000)
  ))
}